# ch14 statistic 

In [1]:
import numpy as np
import scipy.stats as spstats

In [2]:

data = np.random.randint(100,700,90)
data

array([578, 117, 249, 303, 610, 288, 271, 491, 498, 209, 483, 622, 483,
       381, 416, 457, 336, 272, 355, 658, 228, 153, 229, 596, 115, 401,
       686, 396, 134, 171, 434, 224, 272, 541, 688, 510, 277, 398, 574,
       690, 476, 147, 347, 230, 676, 441, 517, 250, 540, 250, 418, 210,
       202, 379, 439, 150, 669, 403, 125, 503, 289, 446, 507, 380, 440,
       268, 120, 240, 376, 653, 557, 142, 667, 256, 332, 439, 220, 199,
       247, 442, 661, 621, 687, 685, 544, 338, 614, 319, 658, 195])

In [3]:
#1)mean
np.mean(data)

396.75555555555553

In [4]:
#2)median 
np.median(data)

397.0

In [ ]:
#3) weighted mean 
#create a matrix for 5 employees with scores (1-100) each column represent the following 
#c1 : technical skills
#c2: interpersonal skill
#c3: managerical skill
#c4: communication skill
#c5: decision malking skills

#calculate , the wighted average of each employee , given the foll weights of each skill
#c1: -10%
#c2: -15%
#c3: -20%
#c4: -40% 
#c5: -15%

In [11]:
c1= np.random.randint(1,101,5)
c1

array([53, 11, 39, 76, 30])

In [12]:
c2= np.random.randint(1,101,5)
c2

array([61, 70, 96, 41, 11])

In [13]:
c3= np.random.randint(1,101,5)
c3

array([82,  5, 63, 50, 25])

In [14]:
c4= np.random.randint(1,101,5)
c4

array([14, 49, 54,  2, 70])

In [15]:
c5= np.random.randint(1,101,5)
c5

array([ 1, 42,  9, 13, 43])

In [16]:
#done by sir
#array broadcast method
scores =  np.random.randint(1,100,25).reshape(-1,5)
scores

array([[88, 54, 85,  9, 79],
       [ 2, 91, 46, 49, 84],
       [15,  4, 79, 60, 27],
       [92, 43, 61, 98, 15],
       [47, 85, 78, 34, 90]])

In [17]:
wt = np.array([0.1,0.15,0.2,0.4,0.15])
wt

array([0.1 , 0.15, 0.2 , 0.4 , 0.15])

In [18]:
np.sum(scores*wt,1)

array([49.35, 55.25, 45.95, 69.3 , 60.15])

In [31]:
#4)geometric mean
ret = np.random.randint(100,200,5,dtype = np.int64)
ret

array([181, 118, 105, 143, 113], dtype=int64)

In [35]:
181* 118* 105* 143* 113

36238011810

In [32]:
ans =1 


In [33]:
for e in ret:
    ans =ans*e

In [34]:
ans

36238011810

In [37]:
# to calculate the nthroot
import sympy 
nth = sympy.integer_nthroot(int(ans),len(ret))   #false - indicate this value or not
nth

(129, False)

In [39]:
print('{} nth rooth of {} is {}'.format(len(ret),ans,nth[0]))

5 nth rooth of 36238011810 is 129


In [42]:
#5)mode
data = np.random.randint(1,5,50)
data

array([1, 4, 4, 4, 3, 2, 3, 2, 1, 1, 4, 2, 3, 3, 4, 1, 1, 2, 2, 3, 4, 2,
       3, 3, 4, 2, 3, 2, 4, 1, 4, 4, 1, 1, 3, 1, 4, 2, 3, 1, 3, 1, 3, 2,
       2, 4, 4, 1, 2, 4])

In [41]:
dir(spstats)

['PearsonRConstantInputWarning',
 'PearsonRNearConstantInputWarning',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_binned_statistic',
 '_constants',
 '_continuous_distns',
 '_discrete_distns',
 '_distn_infrastructure',
 '_distr_params',
 '_hypotests',
 '_multivariate',
 '_rvs_sampling',
 '_stats',
 '_stats_mstats_common',
 '_tukeylambda_stats',
 'absolute_import',
 'alpha',
 'anderson',
 'anderson_ksamp',
 'anglit',
 'ansari',
 'arcsine',
 'argus',
 'bartlett',
 'bayes_mvs',
 'bernoulli',
 'beta',
 'betabinom',
 'betaprime',
 'binned_statistic',
 'binned_statistic_2d',
 'binned_statistic_dd',
 'binom',
 'binom_test',
 'boltzmann',
 'boxcox',
 'boxcox_llf',
 'boxcox_normmax',
 'boxcox_normplot',
 'bradford',
 'brunnermunzel',
 'burr',
 'burr12',
 'cauchy',
 'chi',
 'chi2',
 'chi2_contingency',
 'chisquare',
 'circmean',
 'circstd',
 'circvar',
 'combine_pvalues',
 'contingency',
 'cosine',
 

In [43]:
spstats.mode(data)

ModeResult(mode=array([4]), count=array([14]))

In [47]:
unq = np.unique(data)
unq

array([1, 2, 3, 4])

In [48]:
for e in unq:
    ct = list(data).count(e)
    print('Number = {}, count = {}'.format(e,ct))

Number = 1, count = 12
Number = 2, count = 12
Number = 3, count = 12
Number = 4, count = 14


In [50]:
#2) measure of dispersion
data = np.round(np.random.uniform(10,100,50),1)
data

array([98.7, 12. , 29. , 95.5, 32.6, 88.2, 87.4, 91.8, 33.8, 65.4, 76.9,
       79. , 92.8, 67.8, 34.9, 47.9, 88.5, 83.2, 36.1, 46.1, 10.3, 42.5,
       96.2, 24.7, 60.2, 52.7, 17.9, 43.5, 61. , 20.1, 68.6, 32. , 41.7,
       16.7, 31.7, 27. , 49.1, 21.7, 45.2, 42.1, 77.4, 49. , 75.9, 78.2,
       38. , 73.4, 77.2, 86.3, 83.1, 47.6])

In [51]:
#1)range(max-min)
np.max(data)-np.min(data)

88.4

In [52]:
#2)quartiles
#percentile(<data>,<%>)
np.percentile(data,25)

34.074999999999996

In [54]:
np.percentile(data,10)

21.540000000000003

In [55]:
#write a python script to display all the declies
dec = np.percentile(data,np.arange(10,91,10))
dec

array([21.54, 31.94, 37.43, 44.52, 49.05, 66.36, 76.99, 83.12, 88.83])

In [56]:
#variance and standard deviation
# formula of variance =>   σ^2 = (∑(x - μ)2) / N
np.var(data)

663.8744160000001

In [57]:
np.std(data)

25.76576053602921

In [ ]:
#3) measure of association
#1. Covariance (it show the direction)   ->to check dependance and in dependence
#2. Correlation (it shows the degree)    -> strength of the relation 
                                        # -ve , +ve , zero range(0,1)
#3. Coefficient of Variation
#4. Rank Correlation

In [58]:
#1) covariance
x= np.random.randint(50,100,6)
x

array([55, 69, 97, 58, 83, 98])

In [59]:
y= np.random.uniform(1,5,6)
y

array([4.63194493, 1.59921596, 2.98081343, 4.62658153, 3.46694064,
       2.59430378])

In [61]:
np.cov(x,y)            #PCA - it comes in PCA also 

array([[357.06666667, -12.21400131],
       [-12.21400131,   1.41053171]])

In [62]:
covar =np.cov(x,y)[0,1]
covar

-12.214001310029857

In [63]:
#2) correlation 
np.corrcoef(x,y)

array([[ 1.        , -0.54424178],
       [-0.54424178,  1.        ]])

In [64]:
corr = np.corrcoef(x,y)[0,1]
corr

-0.5442417822273373

In [65]:
#hypothesis testing
#given Z,find area
#cummulativve density function
spstats.norm.cdf(1.645)

0.9500150944608786

In [66]:
spstats.norm.cdf(1.96)

0.9750021048517795

In [67]:
#given area , find z (#z/t-critical values)
#PDF -> percentage point function
spstats.norm.ppf(0.95)

1.6448536269514722

In [68]:
spstats.norm.ppf(0.975)

1.959963984540054

In [70]:
#t- critical value
#ppf(1-alpha,dof)
abs(spstats.t.ppf(0.95,2))

2.919985580355516

In [71]:
#ANOVA critical value
#f.ppf(1-alpha,dof_numerator,dof_denominator)
spstats.f.ppf(0.95,2,20)

3.492828476735632

In [72]:
#CHI-SQ critical value
#chi2.ppf(1-alpha,dof)
spstats.chi2.ppf(0.95,1)

3.841458820694124

In [73]:
#1 sample t-test
#problem statement :-  average weight of a given sample is 30 kgs 
wt =np.random.randint(16,75,24)
len(wt)

24

In [79]:
'''
H0 : average wt is 30
H1: average wt is not 30
this is a 2-tail test 
'''
tail=2
alpha = 0.05
dof = len(wt)-1 


In [ ]:
#if it is a 2-tail test , then alpha has to be divided by 2
if tail ==2:
    alpha/=2

In [75]:
# 1-sample z-test
tt = spstats.ttest_1samp(wt,30)
print(tt)

Ttest_1sampResult(statistic=3.6028792882610916, pvalue=0.0014994336202727684)


In [78]:
tcalc = tt[0]
pvalue =tt[1]


In [82]:
tcalc

3.6028792882610916

In [83]:
pvalue

0.0014994336202727684

In [81]:
tcritical = spstats.t.ppf(1-alpha,dof)
tcritical

1.7138715277470473

In [85]:
#conclusion 
#tcritical and tcalc
if tcalc>tcritical:
    print('Reject H0')
else:
    print('Fail to reject H0')


Reject H0


In [86]:
#alpha and pvalue
if  pvalue<alpha:
  print('Reject H0')
else:
    print('Fail to reject H0')

Reject H0


In [88]:
# 1-sample z-test
#the average mileage of a vehicle is more than 15
mileage = np.round(np.random.uniform(5,28,75),1)
mileage

array([17.9, 27. ,  7.3,  9.2,  7.8, 13.3, 27.9, 11.9,  6.9, 19.8, 24.1,
       23.5,  6.8, 19.4, 18. , 16.1, 20.4,  8.4, 14.2, 23. , 11.2, 13.4,
       17.3, 11. ,  7.1, 23.2,  8.8, 19.6,  6.9, 23.1, 19.9, 15.1, 11.6,
       10.4, 18.2, 14.7, 17.6, 24.1, 24.6,  7.9, 26.1, 24.2, 16.7, 21. ,
       23.6,  6.2, 24.9, 24.4,  5.3, 10.2,  8.2, 27.2, 24.9, 18.1, 17.2,
       17.4, 21.9, 14.6, 23.4, 25.4, 26.3, 14.5, 27. , 19.5,  9.8, 18.3,
        5.5, 26.4, 24.8, 17.4, 21. , 17.4, 23.7, 18.4, 24.6])

In [89]:
'''
Claim :mean>15
opp  : mean<=15
'''

'''
HO : mean =15
H1 : mean >15
'''
tail = 1
alpha= 0.05


In [91]:
if tail == 2:
    alpha/=2

In [92]:
zt = spstats.ttest_1samp(mileage,15)
zt

Ttest_1sampResult(statistic=3.0973552920383405, pvalue=0.0027586091729412403)

In [93]:
zcalc = zt[0]
zcalc

3.0973552920383405

In [94]:
pvalue = zt[1]
pvalue

0.0027586091729412403

In [95]:
#z-critical 
zcritical = spstats.norm.ppf(1-alpha)
zcritical

1.6448536269514722

In [96]:
#conclusion 
if zcalc>zcritical:
    print('Reject H0')
else:
    print('Fail to reject H0')

#same as above

Reject H0


In [ ]:
#ANOVA test
#check if the means of n-samples have same mean
'''
H0: mu1=mu2=mu3=...mun
H1: mu1<>mu2<>mu3...
'''

#application in ML is feature select , in linear regression (x feature category , y variable is cont)



In [97]:
#check if the average petrol prices are similar across different cities
delhi =np.round( np.random.uniform(90,100,10),1)
kolkata = np.round( np.random.uniform(85,96,10),1)
chennai =np.round( np.random.uniform(92,99,10),1)
bang = np.round( np.random.uniform(95,101,10),1)
mum = np.round( np.random.uniform(93,100,10),1)

In [98]:
fs = spstats.f_oneway(delhi,kolkata,chennai,bang,mum)
fs

F_onewayResult(statistic=15.00357836747743, pvalue=7.259475602508958e-08)

In [ ]:
'''
housetype    houseprice
1-bhk 
    30
       --
       -- 
1.5-bhk 
      19
        --
        --
2bhk  
     50
        --
        --
3bhk 
     45
        --
        --
        '''

In [104]:
#CHISQUARE test
#chect if 2 categorical varaibale are indepedent
'''

'''

#example of malaria 
import pandas as pd

In [105]:
city =['mumbai']*500 +['delhi']*400
city

['mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',
 'mumbai',

In [106]:
cases = ['yes']*12 +['no']*488 +['yes']*7 +['no']*393
cases

['yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 

In [112]:
data = pd.DataFrame({'city':city,'malaria':cases})
data

city malaria
0    mumbai     yes
1    mumbai     yes
2    mumbai     yes
3    mumbai     yes
4    mumbai     yes
..      ...     ...
895   delhi      no
896   delhi      no
897   delhi      no
898   delhi      no
899   delhi      no

[900 rows x 2 columns]

In [113]:
#convert the dataset to cross tab
ct = pd.crosstab(data.city,data.malaria)   #crosstab -> count
ct

malaria   no  yes
city             
delhi    393    7
mumbai   488   12

In [114]:
#chisquare test
spstats.chi2_contingency(ct)

(0.19423203297688052,
 0.6594174287603682,
 1,
 array([[391.55555556,   8.44444444],
        [489.44444444,  10.55555556]]))

In [116]:
#chisquare test
chisq = spstats.chi2_contingency(ct)

In [117]:
#return values 
pval = chisq[0]
chicalc = chisq[1]
dof = chisq[2]

In [118]:
pval

0.19423203297688052

In [119]:
chicalc

0.6594174287603682

In [120]:
dof

1

In [ ]:
#conclusion